---
- name: "Setting the hostname of the server"
  when:
    - hostname is defined
  block:
    - name: "Setting system hostname"
      ansible.builtin.hostname:
        name: "{{ hostname }}{{ ('.' + domain) if domain is defined else '' }}"

    - name: "Setting the hostname in the /etc/rc.conf"
      ansible.builtin.lineinfile:
        path: "/etc/rc.conf"
        regexp: "hostname="
        line: "hostname={{ hostname }}{{ ('.' + domain) if domain is defined else '' }}"
        state: "present"
