---
- name: "Setting the name of the server"
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: "Setting the hostname in the /etc/rc.conf"
  ansible.builtin.lineinfile:
    path: "/etc/rc.conf"
    regexp: "hostname="
    line: "hostname={{ hostname }}"
    state: "present"
