---
- name: "Ansible Galaxy packages"
  community.general.ansible_galaxy_install:
    type: "{{ item.type | default('collection') }}"
    name: "{{ item.name }}"
    dest: "{{ item.dest | default(omit) }}"
    no_deps: "{{ item.no_deps | default(omit) }}"
    requirements_file: "{{ item.requirements_file | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
  loop: "{{ packages | default([]) }}"
  register: "output"
