---
- name: "Waiting for cloud-init / user-data to finish"
  ansible.builtin.command:
    cmd: "cloud-init status --wait"
  register: "cloud_init_status"
  changed_when: false
  failed_when: false

- name: "Ensure no other package operations are running"
  ansible.builtin.shell: |
    killall -q apt-get dpkg || true
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done
  changed_when: false

- name: "Removing apt lock files"
  ansible.builtin.file:
    state: "absent"
    path: "{{ item }}"
  loop:
    - "/var/lib/dpkg/lock"
    - "/var/lib/dpkg/lock-frontend"

- name: "Upgrading the packages"
  ansible.builtin.apt:
    update_cache: "{{ update_cache | default(omit) }}"
    upgrade: "{{ upgrade | default(omit) }}"
  when: (update_cache | default(false)) or (upgrade | default('false')) != 'false'

- name: "Apt packages"
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    upgrade: "{{ item.upgrade | default(omit) }}"
    update_cache: "{{ item.update_cache | default(omit) }}"
    install_recommends: "{{ item.install_recommends | default(omit) }}"
    clean: "{{ item.clean | default(omit) }}"
    autoclean: "{{ item.autoclean | default(omit) }}"
    autoremove: "{{ item.autoremove | default(omit) }}"
  loop: "{{ packages | default([]) }}"
  register: "output"

- name: "Manually upgrading any left over packages"
  ansible.builtin.shell: >-
    set -o pipefail && \
    sudo apt list -u -q 2>/dev/null | grep "/" | cut -d/ -f1 | xargs -n 1 sudo apt install -y
  args:
    executable: "/usr/bin/bash"
  register: "output"
  failed_when: false
  changed_when: output.rc == 0
  when: upgrade is defined and upgrade | bool

- name: "Removing dependencies that are no longer required and unnecessary packages from the cache"
  ansible.builtin.apt:
    autoclean: "{{ autoclean | default(omit) }}"
    autoremove: "{{ autoremove | default(omit) }}"
  when: (autoclean | default(false)) or (autoremove | default(false))
