---
- name: "Waiting for cloud-init / user-data to finish"
  ansible.builtin.command:
    cmd: "cloud-init status --wait"
  register: "cloud_init_status"
  changed_when: false
  failed_when: "'status: done' not in cloud_init_status.stdout"

- name: "Ensure no other package operations are running"
  ansible.builtin.shell: |
    killall -q apt-get dpkg || true
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done
  changed_when: false

- name: "Removing apt lock files"
  ansible.builtin.file:
    state: "absent"
    path: "{{ item }}"
  loop:
    - "/var/lib/dpkg/lock"
    - "/var/lib/dpkg/lock-frontend"

- name: "Upgrading the packages"
  ansible.builtin.apt:
    update_cache: "{{ update_cache | default(true) }}"
    upgrade: "{{ upgrade | default('safe') }}"
  when: update_cache is defined or upgrade is defined

- name: "Apt packages"
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    upgrade: "{{ item.upgrade | default(omit) }}"
    update_cache: "{{ item.update_cache | default(omit) }}"
    install_recommends: "{{ item.install_recommends | default(omit) }}"
    clean: "{{ item.clean | default(omit) }}"
    autoclean: "{{ item.autoclean | default(omit) }}"
    autoremove: "{{ item.autoremove | default(omit) }}"
  loop: "{{ packages | default([]) }}"
  register: "output"

- name: "Manually upgrading any left over packages"
  ansible.builtin.shell: >-
    set -o pipefail && \
    sudo apt list -u -q 2>/dev/null | grep "/" | cut -d/ -f1 | xargs -n 1 sudo apt install -y
  args:
    executable: "/usr/bin/bash"
  register: "output"
  failed_when: false
  changed_when: output.rc == 0
  when: upgrade is defined
