---
- name: Updating apt repository and cache
  ansible.builtin.apt:
    update_cache: true

- name: Apt packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    update_cache: "{{ item.update_cache | default(omit) }}"
  loop: "{{ packages }}"
  register: "output"
