---
- name: "Checking if the apt_news is true"
  ansible.builtin.shell: >-
    set -o pipefail && \
    sudo pro config show apt_news | cut -d' ' -f2
  args:
    executable: "/usr/bin/bash"
  register: "apt_news_active"
  changed_when: false

- name: "Setting apt_news to false"
  ansible.builtin.shell: >-
    set -o pipefail && \
    sudo pro config set apt_news=false
  args:
    executable: "/usr/bin/bash"
  register: "output"
  changed_when: output.rc == 0
  when: apt_news_active.stdout | bool
