---
- name: "Installing Docker dependencies"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - name: "apt-transport-https"
      - name: "ca-certificates"
      - name: "curl"
      - name: "software-properties-common"

- name: "Setting Docker GPG key path"
  ansible.builtin.set_fact:
    docker_gpg_file: "/usr/share/keyrings/docker.asc"

- name: "Adding Docker signing key"
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    dest: "{{ docker_gpg_file }}"
    mode: "0644"
    force: true

- name: "Configuring Docker repository"
  ansible.builtin.deb822_repository:
    name: "docker"
    state: "present"
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - "stable"
    architectures:
      - "amd64"
    signed_by: "{{ docker_gpg_file }}"

- name: "Installing apt packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    packages:
      - name: "docker-ce"
        install_recommends: true
      - name: "docker-ce-cli"
      - name: "containerd.io"
      - name: "docker-buildx-plugin"
      - name: "docker-compose-plugin"
        autoremove: true
        autoclean: true
      - name: "docker-registry"
  notify:
    - "Restarting and Enabling docker"

- name: "Forcing all notified handlers to run at this point"
  ansible.builtin.meta: "flush_handlers"

- name: "Setting the user variable if not defined"
  when:
    - user is not defined
  ansible.builtin.set_fact:
    user: "{{ lookup('env', 'USER') }}"

- name: "Adding current user to the docker group"
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - "docker"
    append: true
