---
- name: "Copying the jail config file to the Fail2ban folder"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('640') }}"
  loop: "{{ rules | default([]) }}"
  register: "output"
  notify:
    - "Restarting and Enabling fail2ban"
