---
- name: "Installing apt packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    packages:
      - { name: "google-chrome-stable" }
