---
- name: "Adding Google Chrome signing key"
  ansible.builtin.get_url:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    dest: "/etc/apt/trusted.gpg.d/google-chrome.asc"
    mode: "0644"

- name: "Configuring Google Chrome repository"
  ansible.builtin.deb822_repository:
    name: "google-chrome"
    state: "present"
    uris: "http://dl.google.com/linux/chrome/deb/"
    suites:
      - "stable"
    components:
      - "main"
    architectures:
      - "amd64"
    signed_by: "/etc/apt/trusted.gpg.d/google-chrome.asc"

- name: "Installing apt packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    packages:
      - { name: "google-chrome-stable" }

- name: "Removing legacy Google Chrome repository list file added by post-install script"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/google-chrome.list"
    state: "absent"
