---
- name: "Adding HashiCorp signing key"
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "/etc/apt/trusted.gpg.d/hashicorp.asc"
    mode: "0644"

- name: "Configuring HashiCorp repository"
  ansible.builtin.deb822_repository:
    name: "hashicorp"
    state: "present"
    uris: "https://apt.releases.hashicorp.com"
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - "main"
    architectures:
      - "amd64"
    signed_by: "/etc/apt/trusted.gpg.d/hashicorp.asc"

- name: "Installing HashiCorp packages"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    packages:
      - name: "packer"
        state: "latest"
        handler_to_notify: "Enabling Packer autocomplete"
      - name: "terraform"
        state: "latest"
        handler_to_notify: "Enabling Terraform autocomplete"
      - name: "vault"
        state: "latest"

- name: "Forcing handler execution"
  ansible.builtin.meta: "flush_handlers"
