---
- name: "Adding HashiCorp signing key"
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "/etc/apt/trusted.gpg.d/hashicorp.asc"
    mode: "0644"

- name: "Adding repository into sources list"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc]  https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: "hashicorp"
    state: "present"

- name: "Installing apt packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    packages:
      - {name: "packer", update_cache: true}
      - {name: "terraform", update_cache: true}
  notify:
    - "HashiCorp Auto Completition"

- name: "Force all notified handlers to run at this point, not waiting for normal sync points"
  ansible.builtin.meta: "flush_handlers"
