---
- name: "Adding HashiCorp signing key"
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "/etc/apt/trusted.gpg.d/hashicorp.asc"
    mode: "0644"

- name: "Adding repository into sources list"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc]  https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: "hashicorp"
    state: "present"

- name: "Installing apt packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    packages:
      - {name: "packer", state: "latest", handler_to_notify: "Enable Packer autocomplete"}
      - {name: "terraform", state: "latest", handler_to_notify: "Enable Terraform autocomplete"}
      - {name: "vault", state: "latest"}

- name: "Force all notified handlers to run at this point, not waiting for normal sync points"
  ansible.builtin.meta: "flush_handlers"
