---
- name: "Importing the apt task"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    packages:
      - {name: "build-essential", state: "latest"}  # Make and compiler for building the helper.
      - {name: "libsecret-1-0", state: "latest"}  # To save passwords in the secret store.
      - {name: "libsecret-1-dev", state: "latest"}  # To compile libsecret. By default, it is not.

- name: "Creating variable with the path of libsecret"
  ansible.builtin.set_fact:
    libsecret_path: "/usr/share/doc/git/contrib/credential/libsecret"
    libsecret_binary: "git-credential-libsecret"

- name: "Compiling libsecret"
  community.general.make:
    chdir: "{{ libsecret_path }}"

- name: "Installing libsecret credential helper binary"
  ansible.builtin.copy:
    src: "{{ libsecret_path }}/{{ libsecret_binary }}"
    dest: "/usr/local/bin/{{ libsecret_binary }}"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: true
