---
- name: "Importing the apt task"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt.yml"
  vars:
    update_cache: true
    packages:
      - {name: "libsecret-1-0", state: "latest"}  # To save passwords in the secret store.
      - {name: "libsecret-1-dev", state: "latest"}  # To compile libsecret. By default, it is not.

- name: "Creating variable with the path of libsecret"
  ansible.builtin.set_fact:
    libsecret_path: "/usr/share/doc/git/contrib/credential/libsecret"

- name: "Compiling libsecret"
  community.general.make:
    chdir: "{{ libsecret_path }}"

- name: "Adding libsecret path to PATH"
  when: ansible_env.PATH is not search(libsecret_path)
  ansible.builtin.lineinfile:
    path: "/etc/environment"
    regexp: "PATH="
    line: 'PATH="{{ ansible_env.PATH }}:{{ libsecret_path }}"'
    state: "present"
