---
- name: Ensure the pip package is installed and in its latest version
  pip:
    name: "pip"
    state: "latest"

- name: Python packages
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ packages }}"
  register: "output"  
