---
- name: Ensure the pip package is installed
  pip:
    name: "pip"
    state: "present"

- name: Python packages
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ packages }}"
  register: "output"
