---
- name: "Ensure the pipx package is installed"
  community.general.pipx:
    name: "pipx"
    state: "present"

- name: "Python packages"
  community.general.pipx:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ packages | default([]) }}"
  register: "output"
