---
- name: "Ensure the pipx package is installed"
  community.general.pipx:
    name: "pipx"
    state: "present"

- name: "Ensure pipx path is set"
  become: false
  ansible.builtin.command: "pipx ensurepath"
  when: pipx_path not in ansible_env.PATH
  vars:
    pipx_path: "{{ '~/.local/bin' | expanduser }}"
  changed_when: false

- name: "Python packages"
  become: false
  community.general.pipx:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    install_apps: "{{ item.install_apps | default(omit) }}"
    install_deps: "{{ item.install_deps | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    include_injected: "{{ item.include_injected | default(omit) }}"
    index_url: "{{ item.index_url | default(omit) }}"
    python: "{{ item.python | default(omit) }}"
    system_site_packages: "{{ item.system_site_packages | default(omit) }}"
  loop: "{{ packages | default([]) }}"
  register: "output"
