---
- name: "Installing Snap packages"
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(omit) }}"
    channel: "{{ item.channel | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ packages | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  register: "snap_installation_result"
