---
- name: "Installing VirtualBox"
  ansible.builtin.include_role:
    name: "common"
    tasks_from: "debian/packages/apt.yml"
  vars:
    update_cache: true
    packages:
      - {name: "virtualbox", state: "latest", install_recommends: true}

- name: "Setting the user variable if not defined"
  when: user is not defined
  ansible.builtin.set_fact:
    user: "{{ lookup('env', 'USER') }}"

- name: "Adding current user to the vboxusers group"
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - "vboxusers"
      - "vboxsf"
    append: true
