---
- name: "Defining conflicting VSCode sources files"
  ansible.builtin.set_fact:
    vscode_conflicting_sources:
      - "/etc/apt/sources.list.d/vscode.sources"
      - "/usr/share/keyrings/microsoft.gpg"

- name: "Removing conflicting VSCode sources files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop: "{{ vscode_conflicting_sources }}"

- name: "Adding Microsoft signing key"
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/etc/apt/trusted.gpg.d/microsoft.asc"
    mode: "0644"

- name: "Adding repository into sources list"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
    filename: "vscode"
    state: "present"

- name: "Installing apt packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    packages:
      - {name: "code", update_cache: true}

- name: "Removing conflicting VSCode sources files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop: "{{ vscode_conflicting_sources }}"
