---
- name: "Defining conflicting VSCode sources files"
  ansible.builtin.set_fact:
    vscode_conflicting_sources:
      - "/etc/apt/sources.list.d/vscode.sources"
      - "/usr/share/keyrings/microsoft.gpg"

- name: "Removing conflicting VSCode sources files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop: "{{ vscode_conflicting_sources | default([]) }}"

- name: "Adding Microsoft signing key"
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/etc/apt/trusted.gpg.d/microsoft.asc"
    mode: "0644"

- name: "Configuring VSCode repository"
  ansible.builtin.deb822_repository:
    name: "vscode"
    state: "present"
    uris: "https://packages.microsoft.com/repos/code"
    suites:
      - "stable"
    components:
      - "main"
    architectures:
      - "amd64"
    signed_by: "/etc/apt/trusted.gpg.d/microsoft.asc"

- name: "Installing VS Code"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/packages/apt"
  vars:
    update_cache: true
    packages:
      - { name: "code" }
