---
- name: "Managing vscode extentions"
  become: false
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/vscode-extention.yml"
  vars:
    extentions:
      - {name: "redhat.ansible"}
      - {name: "redhat.vscode-yaml"}
      - {name: "wholroyd.jinja"}
      - {name: "HashiCorp.terraform"}
      - {name: "4ops.packer"}
      - {name: "ms-vscode-remote.remote-ssh"}
      - {name: "vscjava.vscode-java-pack"}
      - {name: "redhat.java"}
      - {name: "tomoki1207.pdf"}
