---
- name: "Creating the alias copy and paste in ~/.bashrc"
  become: false
  ansible.builtin.blockinfile:
    path: "~/.bashrc"
    marker: "# {mark} Linux Xclip Copy and Paste"
    block: |
      alias copy='xclip -selection clipboard'
      alias paste='xclip -selection clipboard -o'
  notify: "Refresh ~/.bashrc"

- name: "Setting up the forward of the display on SSH connections"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/ssh_config"
    regexp: "ForwardX11 no"
    line: "    ForwardX11 yes"
    state: "present"
  notify: "Restarting the SSH server"
