---
- name: "Adding the user xrdp to group 'ssl-cert'"
  ansible.builtin.user:
    name: "xrdp"
    groups: "ssl-cert"
    append: true
  notify: "Restart xrdp"

- name: "Editing the startwm.sh file to avoid the Black Screen problem"
  ansible.builtin.blockinfile:
    path: "/etc/xrdp/startwm.sh"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertbefore: "test -x"
    block: |
      export GNOME_SHELL_SESSION_MODE=ubuntu
      export XDG_CURRENT_DESKTOP=ubuntu:GNOME

      Unset DBUS_SESSION_BUS_ADDRESS
      Unset XDG_RUNTIME_DIR
  register: "output"
  notify: "Restart xrdp"

- name: "Copying allow color managed device file to the target host"
  ansible.builtin.copy:
    src: "45-allow-colord.pkla"
    dest: "/etc/polkit-1/localauthority/50-local.d/"
    mode: "preserve"
  notify: "Restart xrdp"
