---
- name: "Searching for log and temp files that can be removed"
  ansible.builtin.find:
    paths:
      - "/var/log"
      - "/var/tmp"
      - "/tmp"
    patterns: "*.gz,*.log.*"
    recurse: true
  register: "temp_files_to_delete"

- name: "Removing unnecessary files"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "absent"
  loop: "{{ temp_files_to_delete.files | default([]) }}"
  loop_control:
    index_var: "index"
    label: "{{ index }} - {{ item.path }}"

- name: "Cleaning cloud-init data"
  # No native Ansible module exists for cloud-init clean.
  ansible.builtin.command: "cloud-init clean"
  register: "cloud_init_result"
  changed_when: cloud_init_result.rc == 0
  failed_when: cloud_init_result.rc != 0

- name: "Removing cloud-init networking configuration file"
  ansible.builtin.file:
    path: "/etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg"
    state: "absent"

- name: "Syncing filesystems to disk"
  # No native Ansible module exists for sync.
  ansible.builtin.command: "sync"
  changed_when: false

- name: "Removing the history of terminal commands"
  # No native Ansible module exists to clear Bash history.
  ansible.builtin.shell: >-
    set -o pipefail; \
    history -cw; \
    echo > ~/.bash_history
  args:
    executable: "/usr/bin/bash"
  register: "history_result"
  changed_when: history_result.rc == 0
  failed_when: (history_result.rc != 0)
