---
- name: "Setting path for user's NSS certificate database"
  when:
    - nssdb_path is not defined
  ansible.builtin.set_fact:
    nssdb_path: "{{ lookup('env', 'HOME') }}/.pki/nssdb"

- name: "Checking if the user's NSS database directory exists at '{{ nssdb_path }}'"
  ansible.builtin.stat:
    path: "{{ nssdb_path }}"
  register: "nssdb_stat"

- name: "Creating the folder '{{ nssdb_path }}'"
  when:
    - not nssdb_stat.stat.exists
  ansible.builtin.file:
    path: "{{ nssdb_path }}"
    state: "directory"
    recurse: true

- name: "Initializing an empty database at '{{ nssdb_path }}'"
  when:
    - not nssdb_stat.stat.exists
  # No native Ansible module exists for certutil.
  ansible.builtin.command: "certutil -N -d sql:{{ nssdb_path }} --empty-password"
  register: "nssdb_result"
  changed_when: nssdb_result.rc == 0

- name: "Checking if certificate files exist"
  ansible.builtin.stat:
    path: "{{ item.path }}"
  loop: "{{ nssdb_certificates | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  register: "nssdb_cert_stats"

- name: "Checking if certificates already exist in '{{ nssdb_path }}'"
  when:
    - nssdb_cert_stats.results[idx].stat.exists
  # No native Ansible module exists for certutil.
  ansible.builtin.command: "certutil -L -d sql:{{ nssdb_path }} -n {{ item.name }}"
  loop: "{{ nssdb_certificates | default([]) }}"
  loop_control:
    index_var: idx
    label: "{{ item.name }}"
  register: "nssdb_existing_certs"
  changed_when: false
  failed_when: false

- name: "Installing the certificates at '{{ nssdb_path }}'"
  when:
    - nssdb_cert_stats.results[idx].stat.exists
    - nssdb_existing_certs.results[idx].rc != 0
  # No native Ansible module exists for certutil.
  ansible.builtin.command: >
    certutil -A -d 'sql:{{ nssdb_path }}'
    -t '{{ item.trust }}'
    -n '{{ item.name }}'
    -i '{{ item.path }}'
  loop: "{{ nssdb_certificates | default([]) }}"
  loop_control:
    index_var: idx
    label: "{{ item.name }}"
  register: "nssdb_cert_check_result"
  changed_when: nssdb_cert_check_result.rc == 0
  failed_when: (nssdb_cert_check_result.rc != 0)
