---
- name: "Setting up Brazilian NTP servers"
  ansible.builtin.lineinfile:
    path: "/etc/systemd/timesyncd.conf"
    regexp: "NTP="
    line: "NTP={{ ntp_servers }}"
    state: "present"
  register: "output"
  notify: "Restart Systemd-Timesyncd"
