---
- name: "Creating variables"
  ansible.builtin.set_fact:
    ssh_path: "{{ temp_ssh_path }}"
    ca_host_private_key_path: "{{ temp_ssh_path }}/ca_host_key"
    ca_host_public_key_path: "{{ temp_ssh_path }}/ca_host_key.pub"
    host_key_path: "{{ temp_ssh_path }}"
  vars:
    temp_ssh_path: "/etc/ssh"

- name: "Changing the permission so the file can be copied to the target host"
  delegate_to: "{{ delegate_to | default('localhost') }}"
  run_once: true
  ansible.builtin.file:
    path: "{{ ca_host_private_key_path }}"
    mode: "0644"

- name: "Copying the Certificate Authority (CA) private and public keys to the target host"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - {src: "{{ ca_host_private_key_path }}", dest: "{{ ca_host_private_key_path }}", mode: "0600"}
    - {src: "{{ ca_host_public_key_path }}", dest: "{{ ca_host_public_key_path }}", mode: "0644"}

- name: "Changing the permission back to its original value"
  delegate_to: "{{ delegate_to | default('localhost') }}"
  run_once: true
  ansible.builtin.file:
    path: "{{ ca_host_private_key_path }}"
    mode: "0600"

- name: "Signing the Host OpenSSH keypair with the CA key"
  community.crypto.openssh_cert:
    type: "host"
    signing_key: "{{ ca_host_private_key_path }}"
    public_key: "{{ host_key_path }}/ssh_host_{{ item.name }}_key"
    path: "{{ host_key_path }}/ssh_host_{{ item.name }}_key-cert.pub"
    regenerate: "{{ item.regenerate | default('full_idempotence') }}"
    valid_from: "{{ item.valid_from | default('always') }}"
    valid_to: "{{ item.valid_to | default('forever') }}"
    principals: "{{ item.principals | default(omit) }}"
    state: "present"
  loop:
    - { name: "ecdsa", principals: "{{ principals }}" }
    - { name: "ed25519", principals: "{{ principals }}" }
    - { name: "rsa", principals: "{{ principals }}" }
  vars:
    principals: ["{{ ansible_hostname }}", "{{ ansible_hostname }}.{{ domain }}"]
  register: "cert_output"
  notify: "Restarting the SSH server"

- name: "Editing the known_hosts file to trust servers with SSH keys signed by the Certificate Authority (CA) OpenSSH keypair"
  ansible.builtin.lineinfile:
    path: "{{ ssh_path }}/ssh_known_hosts"
    line: "@cert-authority * {{ lookup('ansible.builtin.file', ca_host_public_key_path) }}"
    create: true
    mode: "0644"
  register: "output"
  notify: "Restarting the SSH server"

- name: "Deleting the Certificate Authority (CA) signing key from the target host"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "{{ ca_host_private_key_path }}"
    - "{{ ca_host_public_key_path }}"

- name: "Copying default ssh config file to the target host"
  ansible.builtin.copy:
    src: "ssh.conf"
    dest: "{{ ssh_path }}/sshd_config.d/"
    mode: "preserve"
  notify: "Restarting the SSH server"
