---
- name: "Creating variables"
  ansible.builtin.set_fact:
    ssh_path: "{{ temp_ssh_path }}"
    ca_host_key_path: "{{ temp_ssh_path }}/ca_host_key"
    host_key_path: "{{ temp_ssh_path }}"
  vars:
    temp_ssh_path: "/etc/ssh"

- name: "Creating the Host OpenSSH keypair"
  community.crypto.openssh_keypair:
    path: "{{ host_key_path }}/ssh_host_{{ item.name }}_key"
    type: "{{ item.name }}"
    size: "{{ item.size | default(omit) }}"
    regenerate: "{{ item.regenerate | default('always') }}"
    comment: "{{ item.name }} key"
    state: "present"
  loop:
    - { name: "ecdsa" }
    - { name: "ed25519" }
    - { name: "rsa", size: 2048 }
  register: "host_output"
  notify: "Restarting the SSH server"

- name: "Changing the permission so the file can be copied to the target host"
  delegate_to: "localhost"
  ansible.builtin.file:
    path: "{{ ca_host_key_path }}"
    mode: "0644"

- name: "Copying the Certificate Authority (CA) signing key to the target host"
  ansible.builtin.copy:
    src: "{{ ca_host_key_path }}"
    dest: "{{ ca_host_key_path }}"
    mode: "0600"

- name: "Changing the permission back to its original value"
  delegate_to: "localhost"
  ansible.builtin.file:
    path: "{{ ca_host_key_path }}"
    mode: "0600"

- name: "Signing the Host OpenSSH keypair with the CA key"
  community.crypto.openssh_cert:
    type: "host"
    signing_key: "{{ ca_host_key_path }}"
    public_key: "{{ host_key_path }}/ssh_host_{{ item.name }}_key"
    path: "{{ host_key_path }}/ssh_host_{{ item.name }}_key-cert.pub"
    regenerate: "{{ item.regenerate | default('full_idempotence') }}"
    valid_from: "{{ item.valid_from | default('always') }}"
    valid_to: "{{ item.valid_to | default('forever') }}"
    principals: "{{ item.principals | default(omit) }}"
    state: "present"
  loop:
    - { name: "ecdsa" }
    - { name: "ed25519" }
    - { name: "rsa"}
  register: "cert_output"
  notify: "Restarting the SSH server"

- name: "Deleting the Certificate Authority (CA) signing key from the target host"
  ansible.builtin.file:
    path: "{{ ca_host_key_path }}"
    state: "absent"

- name: "Copying default ssh config file to the target host"
  ansible.builtin.copy:
    src: "ssh.conf"
    dest: "{{ ssh_path }}/sshd_config.d/"
    mode: "preserve"
  notify: "Restarting the SSH server"
