---
- name: "Copying certificate to host"
  ansible.builtin.copy:
    src: "{{ ssl_ca_certificate_path }}"
    dest: "/usr/local/share/ca-certificates/"
    mode: "0644"
  notify: "Update CA Certificates"

- name: "Editing the known_hosts file to trust servers with SSH keys signed by the Certificate Authority (CA) OpenSSH keypair"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/ssh_known_hosts"
    line: "@cert-authority * {{ lookup('ansible.builtin.file', ssh_ca_certificate_path) }}"
    create: true
    mode: "0644"
  notify: "Restarting the SSH server"

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: "flush_handlers"
