---
- name: "Installing CA certificates as trusted"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ca_certificates_path }}/"
    mode: "0644"
  loop: "{{ ca_certificates | default([]) }}"
  notify:
    - "Updating the CA list - Debian"

- name: "Configuring SSH known hosts for CA-signed server keys"
  ansible.builtin.lineinfile:
    path: "{{ ssh_known_hosts }}"
    line: "@cert-authority * {{ lookup('ansible.builtin.file', item) }}"
    create: true
    mode: "0644"
  loop: "{{ ssh_host_ca_keys | default([]) }}"
  notify:
    - "Restarting the SSH server"

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: "flush_handlers"
