---
- name: Adding the fingerprint of host {{ host.name }} into the know_hosts file
  ansible.builtin.known_hosts:
    name: "{{ host.name }}"
    key: "{{ host.key }}"
    state: "{{ item.state | default('present') }}"
    hash_host: "{{ item.hash_host | default('false') }}"
  when: host.name | length > 0 and host.key | length > 0
  register: "output"
