---
- name: "Ensure the .ssh directory exists"
  run_once: true
  delegate_to: "{{ delegate_to | default('localhost') }}"
  become: "{{ become | default(false) }}"
  ansible.builtin.file:
    path: "~/.ssh/"
    state: "directory"
    mode: "0700"

- name: "Retrieving the fingerprint of the host"
  delegate_to: "{{ delegate_to | default('localhost') }}"
  ansible.builtin.set_fact:
    fingerprints: "{{ {'name': _host_name, 'key': _host_key} }}"
  vars:
    # ssh_key_type: "rsa"
    # ssh_key_type: "ecdsa"
    _ssh_key_type: "{{ ssh_key_type | default('ed25519') }}"
    _host_name: "{{ host_name | default(inventory_hostname) }}"
    _host_key: "{{ host_key | default(lookup('pipe', 'ssh-keyscan -t ' + _ssh_key_type + ' ' + _host_name, errors='ignore')) }}"

- name: "Printing the fingerprint (name and key)"
  ansible.builtin.debug:
    msg: "{{ fingerprints }}"
  when: debug | bool

- name: "Ensure the fingerprint is present in the known_hosts file"
  ansible.builtin.include_tasks: "{{ path_debian_known_hosts_add }}"
  vars:
    host: "{{ fingerprints }}"
