---
- name: "Apply sysctl configuration"
  ansible.builtin.command: "/sbin/sysctl --system"
  register: "output"
  changed_when: output.rc == 0

- name: "Update Grub"
  ansible.builtin.command: "update-grub"
  register: "output"
  changed_when: output.rc == 0

- name: "Reconfigure Timezone"
  ansible.builtin.command: "dpkg-reconfigure --frontend noninteractive tzdata"
  register: "output"
  changed_when: output.rc == 0

- name: "Restart Timesyncd"
  ansible.builtin.systemd:
    name: "systemd-timesyncd"
    state: "restarted"
  register: "output"

- name: "Restart Chronyd"
  ansible.builtin.systemd:
    name: "chronyd"
    state: "restarted"
  register: "output"

- name: "Restart Systemd-Resolved"
  ansible.builtin.systemd:
    name: "systemd-resolved"
    state: "restarted"
  register: "output"

- name: "Restart Xrdp"
  ansible.builtin.systemd:
    name: "xrdp"
    state: "restarted"
    enabled: true
  register: "output"

- name: "Restart Bind9"
  ansible.builtin.systemd:
    name: "bind9"
    state: "restarted"
    enabled: true
  register: "output"

- name: "Restart Chrony"
  ansible.builtin.systemd:
    name: "chrony"
    state: "restarted"
    enabled: true
  register: "output"

- name: "Enable Packer autocomplete"
  become: false
  ansible.builtin.command: "packer -autocomplete-install"
  register: "autocomplete_output"
  failed_when:
    - autocomplete_output.rc != 0
    - "'already installed' not in autocomplete_output.stderr"
  changed_when:
    - autocomplete_output.rc == 0

- name: "Enable Terraform autocomplete"
  become: false
  ansible.builtin.command: "terraform -install-autocomplete"
  register: "autocomplete_output"
  failed_when:
    - autocomplete_output.rc != 0
    - "'already installed' not in autocomplete_output.stderr"
  changed_when:
    - autocomplete_output.rc == 0

- name: "Reboot host"
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 120
    pre_reboot_delay: 0
    post_reboot_delay: 10
    test_command: "whoami"
  register: "output"

- name: "Restart network"
  ansible.builtin.systemd:
    name: "networking"
    state: "restarted"
  poll: 1
  async: 60
  register: "output"

- name: "Restart NetworkManager"
  ansible.builtin.systemd:
    name: "NetworkManager"
    state: "restarted"
  poll: 1
  async: 60
  register: "output"

- name: "Reload network"
  ansible.builtin.command: "ifreload -a"
  register: "output"
  changed_when: output.rc == 0

- name: "Wait for the network device to reload"
  ansible.builtin.wait_for_connection:
    delay: 1
  register: "output"

- name: "Updating the CA list - Debian"
  ansible.builtin.command: "update-ca-certificates"
  register: "output"
  changed_when: output.rc == 0

- name: "Update CA Certificates FreeBSD"
  ansible.builtin.command: "certctl rehash"
  register: "output"
  changed_when: output.rc == 0

- name: "Restarting and Enabling fail2ban"
  ansible.builtin.systemd:
    name: "fail2ban"
    state: "restarted"
    enabled: true
  register: "output"

- name: "Restarting the SSH server"
  ansible.builtin.systemd:
    name: "ssh"
    state: "restarted"
    enabled: true
  register: "output"
  failed_when: false

- name: "Restarting and Enabling docker"
  ansible.builtin.systemd:
    name: "docker"
    state: "restarted"
    enabled: true
  register: "output"

- name: "Refresh ~/.bashrc"
  become: false
  ansible.builtin.shell: >-
    set -o pipefail && \
    source ~/.bashrc
  args:
    executable: "/usr/bin/bash"
  register: "source_output"
  changed_when: source_output.rc == 0

- name: "Restarting and Enabling keepalived"
  ansible.builtin.systemd:
    name: "keepalived"
    state: "restarted"
    enabled: true
  register: "output"

- name: "Restart qemu-guest-agent"
  ansible.builtin.systemd:
    name: "qemu-guest-agent"
    state: "started"
    enabled: true
  register: "output"

- name: "Netplan Apply"
  ansible.builtin.command: "netplan apply"
  poll: 1
  async: 60
  register: "output"
  changed_when: output.rc == 0

- name: "Start gnome-keyring-daemon"
  ansible.builtin.command: "gnome-keyring-daemon --start --components=secrets,ssh"
  register: "output"
  changed_when: output.rc == 0
