---
- name: "Trying to retrieve the password in order to verify if already exists or it has changed - '{{ password_id }}'"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/passwords/get"

- name: "Adding the password into the Secret Manager - '{{ password_id }}'"
  when: (output.rc == 1 or output.stdout != password)
  become: false
  no_log: "{{ not (debug | default(false)) }}"
  # No native Ansible module exists for secret-tool.
  ansible.builtin.command: "secret-tool store --label='{{ password_id }}' password {{ password_id }}"
  args:
    stdin: "{{ password }}"
    stdin_add_newline: false
  register: "output"
  changed_when: output.rc == 0
