---
- name: "Trying to retrieve the password in order to verify if already exists or it has changed - '{{ password_id }}'"
  ansible.builtin.import_role:
    name: "common"
    tasks_from: "debian/passwords/get"

- name: "Adding the password into the Secret Manager - '{{ password_id }}'"
  when: (password_retrieval_result.rc == 1 or password_retrieval_result.stdout != password)
  no_log: "{{ not (debug | default(false)) }}"
  become: false
  # No native Ansible module exists for secret-tool.
  ansible.builtin.command: "secret-tool store --label='{{ password_id }}' password {{ password_id }}"
  args:
    stdin: "{{ password }}"
    stdin_add_newline: false
  register: "password_storage_result"
  changed_when: password_storage_result.rc == 0
