---
- name: "Installing system-wide Python applications with pipx"
  become: false
  community.general.pipx:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_apps: "{{ item.install_apps | default(omit) }}"
    install_deps: "{{ item.install_deps | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    include_injected: "{{ item.include_injected | default(omit) }}"
    inject_packages: "{{ item.inject_packages | default(omit) }}"
    index_url: "{{ item.index_url | default(omit) }}"
    executable: "/usr/local/bin/pipx"  # Use Homebrew-installed pipx.
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item.name }}"
